name: 'VUL.WIKI DROPS'
description: 'VUL.WIKI DROPS'
author: 'vul.wiki'
branding:
  icon: 'book'
  color: 'blue'
inputs:
  github_token:
    description: 'Github token for the repo'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.PERSONAL_TOKEN }}
